name: feat
description: Do you have a new feature or specification?
title: "[feature] "
labels: ["feat"]
body:
  - type: textarea
    id: feat-description
    attributes:
      label: 📄 Description
      description: Please describe the new feature.
      placeholder: Provide detailed description!
    validations:
      required: true
  - type: textarea
    id: feat-tasks
    attributes:
      label: ✅ Tasks
      description: Please list the tasks that need to be done.
      placeholder: Break them down as much as possible!
    validations:
      required: true
  - type: textarea
    id: feat-notes
    attributes:
      label: 📝 Notes
      description: Any additional notes?
    validations:
      required: false